### ISSUE TITLE
Iterator breaks when adding too many items

### ISSUE THREAD

**Issue by dan-eicher** [rafaelkallis/adaptive-radix-tree#3] opened 2020-09-18 04:05 UTC
This leads to a segfault in art::tree_it::greater_equal

```c++
#include <cstdio>
#include <iostream>

#include "art.hpp"

template <class T>
int tree_len(art::art<T> &tree)
{
    int count = 0;

    for (art::tree_it<T> iter = tree.begin(); iter != tree.end(); iter++) {
        count++;
    }

    return count;
}

int main()
{
    char buffer[5];
    art::art<int> tree;

    for (int i = 0; i < 0x10000; i++) {
        std::snprintf(buffer, 5, "%04X", i);
        tree.set(buffer, new int(i));
        std::cout << buffer << " " << tree_len(tree) << std::endl;
    }

    return 0;
}
```

**Comment by rafaelkallis** [comment] 2020-09-18 12:17
thanks for reporting this and providing replication code snippet. 

Am I correct to assume that the segfault occurs during `iter != tree.end()` (from the code snippet) or does that happen somewhere else?

**Comment by dan-eicher** [comment] 2020-09-18 18:39
From what I can tell from a little digging around it's from creating the iterator from art::begin(), chained down to line to tree_it::greater_equal().

```
<tree_it.hpp: line 87> :

/usr/include/c++/10/bits/stl_stack.h:214: std::stack<_Tp, _Sequence>::reference std::stack<_Tp, _Sequence>::top() [with _Tp = art::node<_object>*; _Sequence = std::deque<art::node<_object>*, std::allocator<art::node<_object>*> >; std::stack<_Tp, _Sequence>::reference = art::node<_object>*&]: Assertion '__builtin_expect(!this->empty(), true)' failed.
Aborted (core dumped)
```

**Comment by rafaelkallis** [comment] 2020-09-20 19:55
From the code snippet I can see you are calling `tree.begin()` for each iteration. Does the segfault happen for the same `i` every time?

**Comment by dan-eicher** [comment] 2020-09-21 23:28
Results I get:
```
"0000" .. "0FFF" -- tree_len is correct
"1000" .. "10FF" -- tree_len returns 0
"1100"                -- Segmentation fault (core dumped)
```

I tried with both clang and gcc and each has the same behaviour.

**Comment by rafaelkallis** [comment] 2020-09-22 20:00
thanks, I'm observing the same results on my end. I will look into it.

**Comment by rafaelkallis** [comment] 2020-09-23 07:50
For reference I created a model of the data structure that shows relevant snapshots of the internal structure.
The following snapshots are depicted:
- `empty` the empty tree;
- `0*` after inserting `"0000" .. "0FFF"`;
- `0*+10*` after inserting `"1000" .. "10FF"`; 
- `0*+10*+1100` after inserting `"1100"`.

We observe:
- correct `tree_len()` any snapshot from `empty` (incl.) to `0*` (incl.);
-  `tree_len() == 0` any snapshot from `0*` (excl.) to `0*+10*` (incl.);
- segfault any snapshot from `0*+10*+1100`

![PXL_20200923_072831874](https://user-images.githubusercontent.com/9661903/93981289-13ea8800-fd80-11ea-95fa-2143e2e11a2d.jpeg)

**Comment by rafaelkallis** [comment] 2020-09-23 12:31
pardon me, the model above is incorrect, I should have interpreted the ascii representation of the keys rather the the raw byte representation. Making a new model...

**Comment by rafaelkallis** [comment] 2020-09-23 12:34
pardon me, the model above is incorrect. I should have used the ascii interpretation of the keys. Making a new model.

**Comment by rafaelkallis** [comment] 2020-09-23 13:06
Here the now hopefully correct model.

![PXL_20200923_130308421](https://user-images.githubusercontent.com/9661903/94016351-48753880-fdae-11ea-9a0a-81a89f0a56af.jpg)

**Comment by rafaelkallis** [comment] 2020-09-23 14:11
I can confirm through debugging that the data structure looks like depicted on the newer "correct" model for snapshot `0*`. Also I notice an odd `prefix_len_` value on the leaf-node of `0000`, investigating further.

![Screenshot from 2020-09-23 16-06-01](https://user-images.githubusercontent.com/9661903/94024140-59767780-fdb7-11ea-8487-340b242cba74.png)

**Comment by rafaelkallis** [comment] 2020-09-25 14:15
The issue has been fixed with the latest release. One important `if` statement was skipped during a check on nodes with empty prefix.

https://github.com/rafaelkallis/adaptive-radix-tree/blob/d78687fa4df37c894eb1e6f37017c7dfd6676258/include/art/tree_it.hpp#L94-L96

Also you code snipped has been added as a test case.
https://github.com/rafaelkallis/adaptive-radix-tree/blob/d78687fa4df37c894eb1e6f37017c7dfd6676258/test/art.cpp#L374-L391

**Closed by rafaelkallis** 2020-09-25 14:15 UTC
Labels: bug
